# Generated by Django 5.2.7 on 2025-10-11 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_claim'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_name', models.CharField(blank=True, max_length=200)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.CharField(blank=True, max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.claim')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
