# Generated by Django 5.2.7 on 2025-10-11 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_claimresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='claimant_email',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='claim',
            name='claimant_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
